# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [1]:
import numpy as np 
onetoten = np.array(range(1,11))
onetoten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [2]:
zero = np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [3]:
evenly_spaced = np.linspace(0,5,10)
evenly_spaced
#evenly_spaced = np.arange([0,6,0.5],  )

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [4]:

identity_matrix = np.identity(5)#.reshape((5,5))
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [5]:
fourbyfour = np.linspace(0,1,16).reshape((4,4))
fourbyfour

array([[0.        , 0.06666667, 0.13333333, 0.2       ],
       [0.26666667, 0.33333333, 0.4       , 0.46666667],
       [0.53333333, 0.6       , 0.66666667, 0.73333333],
       [0.8       , 0.86666667, 0.93333333, 1.        ]])

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [6]:
array_1 = np.arange(1,10)
array_1.shape

(9,)

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [7]:
oneD = np.arange(1,17)
oneD
matrix = oneD.reshape((4,4))
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [8]:
random = np.linspace(1,20)
random
random[2].dtype

dtype('float64')

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [9]:
even_num = np.linspace(2,100,50)
even_num

array([  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
        24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,
        46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,
        68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,
        90.,  92.,  94.,  96.,  98., 100.])

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [10]:
#n =np.random.rand(6,6)
n = np.random.randint(10,50,size= (6,6))
n

array([[36, 37, 10, 19, 22, 22],
       [22, 24, 29, 25, 12, 34],
       [31, 39, 34, 11, 40, 21],
       [23, 33, 45, 38, 42, 49],
       [31, 47, 12, 41, 30, 44],
       [48, 13, 27, 23, 41, 11]])

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [11]:
twoD = np.random.randint(10, size = (2,2))
print(twoD)
submatrix = twoD[1:2]
print(submatrix)


[[0 7]
 [6 6]]
[[6 6]]


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [12]:
S = np.array((1,10))
print(S)
sum = np.sum(S)
sum

[ 1 10]


11

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [13]:
sample = np.linspace(3,100,50)
print(sample)
average = np.mean(sample)
print(average)
median = np.median(sample)
print(median)
standard = np.std(sample)
print(standard)
#mode = np.mode(sample)
#print(mode)

[  3.           4.97959184   6.95918367   8.93877551  10.91836735
  12.89795918  14.87755102  16.85714286  18.83673469  20.81632653
  22.79591837  24.7755102   26.75510204  28.73469388  30.71428571
  32.69387755  34.67346939  36.65306122  38.63265306  40.6122449
  42.59183673  44.57142857  46.55102041  48.53061224  50.51020408
  52.48979592  54.46938776  56.44897959  58.42857143  60.40816327
  62.3877551   64.36734694  66.34693878  68.32653061  70.30612245
  72.28571429  74.26530612  76.24489796  78.2244898   80.20408163
  82.18367347  84.16326531  86.14285714  88.12244898  90.10204082
  92.08163265  94.06122449  96.04081633  98.02040816 100.        ]
51.5
51.5
28.567231834636647


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [14]:
odd_num = np.arange(1,100,2)
odd_num
max = np.max(odd_num)
print(max)
min = np.min(odd_num)
print(min)


99
1


In [15]:
matrix_a = np.random.randint(10,200,size=(5,8))
print(matrix_a)
row_max = np.max(matrix_a, axis = 1) # check for the maximum values rowwise
print(row_max)
col_max = np.max(matrix_a, axis = 0) # Check for the max in column 
print(col_max)

[[ 33  88  70 186  74 194 141 181]
 [160 105 163 185  57  60  12 121]
 [ 45 166 117 148 128  66 117  91]
 [199  37 191  11 186  96 108  80]
 [ 51 116 147  50  96  51 108 119]]
[194 185 166 199 147]
[199 166 191 186 186 194 141 181]


In [16]:
row_max = np.max(matrix_a, axis =1)
print(row_max)

[194 185 166 199 147]


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [17]:
num = np.random.randint(1,100, size = 20)
print(num)
print(num[19])
max_index = np.argmax(num) 
print(max_index)

[ 8 12  3 66  1 77 23 36 47 47 49 97 20 86 47 60 50 42 86 92]
92
11


---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [18]:
seq = np.arange(2,50,5)
seq
reversed = np.flip(seq)
reversed

array([47, 42, 37, 32, 27, 22, 17, 12,  7,  2])

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [19]:
three_matrix = np.random.randint(9, size = (3,3))
three_matrix
prod = np.multiply(three_matrix, three_matrix)
prod

array([[64,  4, 64],
       [ 4,  1,  1],
       [ 9, 49,  4]])

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [20]:
array_2 = np.linspace(0,9,10)
print(array_2)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [21]:
diagonal = np.diag(array_2)
print(diagonal)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [22]:
A = np.random.randint(0,10, size =(2,2))
print(A )
print('\t')
B = np.random.randint(10,20 ,size = (2,2))
print(B)
print('\t')
AB = np.multiply(A,B)
print(AB)

[[1 0]
 [0 8]]
	
[[19 18]
 [17 19]]
	
[[ 19   0]
 [  0 152]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

In [23]:
matrix_3 = np.random.randint( 13,26, size = (2,2))
matrix_3
matrix_3.flatten()

array([13, 22, 20, 14])

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [24]:
m = np.array([10,30])
n = np.array([1,10])
print(m)
print(n)
np.vstack((m,n))
#print(M)
#M = np.expand_dims(m, axis = 0)
#M

[10 30]
[ 1 10]


array([[10, 30],
       [ 1, 10]])

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [25]:
np.hstack((n,m))

array([ 1, 10, 10, 30])

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [26]:
num_1 = np.linspace(1,10)
num_1
np.split(num_1,5)

[array([1.        , 1.18367347, 1.36734694, 1.55102041, 1.73469388,
        1.91836735, 2.10204082, 2.28571429, 2.46938776, 2.65306122]),
 array([2.83673469, 3.02040816, 3.20408163, 3.3877551 , 3.57142857,
        3.75510204, 3.93877551, 4.12244898, 4.30612245, 4.48979592]),
 array([4.67346939, 4.85714286, 5.04081633, 5.2244898 , 5.40816327,
        5.59183673, 5.7755102 , 5.95918367, 6.14285714, 6.32653061]),
 array([6.51020408, 6.69387755, 6.87755102, 7.06122449, 7.24489796,
        7.42857143, 7.6122449 , 7.79591837, 7.97959184, 8.16326531]),
 array([ 8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
         9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])]

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [27]:
element = np.linspace(1,20)
element
np.round(element ,2)

array([ 1.  ,  1.39,  1.78,  2.16,  2.55,  2.94,  3.33,  3.71,  4.1 ,
        4.49,  4.88,  5.27,  5.65,  6.04,  6.43,  6.82,  7.2 ,  7.59,
        7.98,  8.37,  8.76,  9.14,  9.53,  9.92, 10.31, 10.69, 11.08,
       11.47, 11.86, 12.24, 12.63, 13.02, 13.41, 13.8 , 14.18, 14.57,
       14.96, 15.35, 15.73, 16.12, 16.51, 16.9 , 17.29, 17.67, 18.06,
       18.45, 18.84, 19.22, 19.61, 20.  ])

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [28]:
Array = np.array([12,23,17,12,29,3])
print(Array) 
U = np.unique(Array)
print(U)

[12 23 17 12 29  3]
[ 3 12 17 23 29]


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

In [67]:
ds = np.array(range(10,20))
print(ds)
ds[0:] = 45
print(ds)

[10 11 12 13 14 15 16 17 18 19]
[45 45 45 45 45 45 45 45 45 45]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

In [60]:
ds = np.array(range(10,20))
ds
np.sum(ds)

145

-

--

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [29]:
import numpy as np
random_array = np.array(range(0,9,2))
random_array  
np.isin(random_array,0 )

array([ True, False, False, False, False])

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

In [30]:
sort_1= np.random.randint(10, 45, size = 16)
print("Sequence, ",sort_1 )
np.sort(sort_1)

Sequence,  [27 23 36 20 11 30 18 29 29 40 18 11 17 43 12 43]


array([11, 11, 12, 17, 18, 18, 20, 23, 27, 29, 29, 30, 36, 40, 43, 43])

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

In [31]:
sort_2= np.random.randint(10, 45, size = (3,3))
sort_2
print(np.sum(sort_2, axis =1))
print(np.sum(sort_2, axis =0))

[57 93 95]
[61 99 85]


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

In [52]:
y = np.random.randint(12,23,size = (2,3))
print(y)
min = np.min(y)
print(min)
max = np.max(y)
print(max)
diff = max - min
print(diff)
normalize = ((np.subtract(y ,min))*diff)/diff
print(normalize)

[[15 12 22]
 [19 17 21]]
12
22
10
[[ 3.  0. 10.]
 [ 7.  5.  9.]]


---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

In [33]:
U = np.random.randint(1,10,size =(2,2))
print(U)
R = np.random.randint(3,20, size = (2,2))
print(R)
np.matrix.dot(U,R)

[[5 7]
 [1 8]]
[[ 7  3]
 [ 4 15]]


array([[ 63, 120],
       [ 39, 123]])

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

In [34]:
Sqrt_matrix = np.arange(1,17).reshape((4,4))
print(Sqrt_matrix)
np.matrix.trace(Sqrt_matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


34

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

In [35]:
D = np.arange(1,5).reshape((2,2))
print(D)
np.ndarray.swapaxes(D, 0,1)

[[1 2]
 [3 4]]


array([[1, 3],
       [2, 4]])

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

In [36]:
P = np.arange(4,20)
print(P)
np.asmatrix(P)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


matrix([[ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

In [37]:
three_by_three = np.random.randint(10,30, size =(3,3))
print(three_by_three)
np.linalg.det(three_by_three)

[[16 24 18]
 [27 11 18]
 [22 25 19]]


1129.9999999999995

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

In [38]:
two_by_two = np.random.randint(2,10, size = (2,2))
print(two_by_two)
np.linalg.eig(three_by_three)

[[7 5]
 [3 9]]


EigResult(eigenvalues=array([ 59.78181709, -12.23717379,  -1.5446433 ]), eigenvectors=array([[-0.55594609, -0.50107735, -0.4086587 ],
       [-0.54066903,  0.81266187, -0.33731065],
       [-0.63134852, -0.29749314,  0.84806815]]))

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

In [39]:
x_val = np.arange(4).reshape((2,2))
print(x_val)
print('\t')
print(x_val.shape)
y_val = np.arange(4).reshape((2,2))
print(y_val)
print('\t')
print(y_val.shape)
np.linalg.solve( x_val, y_val)

[[0 1]
 [2 3]]
	
(2, 2)
[[0 1]
 [2 3]]
	
(2, 2)


array([[1., 0.],
       [0., 1.]])

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

In [40]:
yvalues = np.random.normal(size =(1,120))
yvalues


array([[-1.23497282, -0.11425414, -1.45669942,  0.82416327, -0.30015356,
        -0.77506173, -2.13641362, -0.37664886, -1.82552735, -2.07817266,
         0.2392238 , -1.22663064, -0.3348498 ,  1.52395579, -0.2088065 ,
        -0.31837588,  0.28479426, -0.45383734, -0.44966873,  0.89667892,
         0.34508471,  0.05871677,  0.69721009, -1.03152312,  0.86909204,
         0.99671453, -0.34372535,  0.81816544,  0.41560531, -0.06143908,
        -1.09854717,  0.89747539, -0.50532956,  0.12894907, -0.63222573,
        -0.14528926, -0.41828263,  0.17014924, -0.48101704,  0.36896002,
         1.12566596, -0.24511298, -0.14108781,  1.42630975, -0.18327128,
         0.22017425,  0.14402597,  0.40135381, -0.32561646, -0.97268283,
        -0.70496099,  0.98514555,  1.06700565,  0.00581248,  0.68247853,
        -1.18670587, -1.24793871,  0.44225872, -0.83544288, -1.1598855 ,
         0.0728497 ,  1.00351989,  0.2756226 , -0.02317385, -0.12757359,
         0.06063085, -1.48553431, -1.03031422, -1.0

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

In [41]:
four_by_four = np.random.randint(10,100, size = (4,4))
print(four_by_four)
np.diag(four_by_four, 0)

[[59 47 79 97]
 [78 46 35 74]
 [26 96 44 42]
 [70 90 88 50]]


array([59, 46, 44, 50])

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

In [42]:
generate = np.random.randint(range(10,50))
generate

array([ 5,  8,  3,  0,  0,  3,  0,  7,  6,  7,  7, 11, 19, 17, 11,  3, 16,
       22,  9, 20, 19,  5, 11, 30, 26,  3, 14, 20,  8,  1, 29, 30, 25,  0,
       17, 25, 21, 32, 11,  2])

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

In [43]:
twoD_array = np.array(range(-2,2)).reshape((2,2))
print(twoD_array)
np.zeros(twoD_array[1]) 

[[-2 -1]
 [ 0  1]]


array([], shape=(0, 1), dtype=float64)

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

In [56]:
C = np.arange(16).reshape((4,4))
C
F = np.random.randint(10,20, size = (4,4))
F
inner = np.inner(C,F)
outer = np.outer(C,F)
print(inner)
print(outer)

[[ 85  99  97  71]
 [317 351 329 275]
 [549 603 561 479]
 [781 855 793 683]]
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 15  13  18  12  13  16  19  15  12  11  19  16  16  12  10  13]
 [ 30  26  36  24  26  32  38  30  24  22  38  32  32  24  20  26]
 [ 45  39  54  36  39  48  57  45  36  33  57  48  48  36  30  39]
 [ 60  52  72  48  52  64  76  60  48  44  76  64  64  48  40  52]
 [ 75  65  90  60  65  80  95  75  60  55  95  80  80  60  50  65]
 [ 90  78 108  72  78  96 114  90  72  66 114  96  96  72  60  78]
 [105  91 126  84  91 112 133 105  84  77 133 112 112  84  70  91]
 [120 104 144  96 104 128 152 120  96  88 152 128 128  96  80 104]
 [135 117 162 108 117 144 171 135 108  99 171 144 144 108  90 117]
 [150 130 180 120 130 160 190 150 120 110 190 160 160 120 100 130]
 [165 143 198 132 143 176 209 165 132 121 209 176 176 132 110 143]
 [180 156 216 144 156 192 228 180 144 132 228 192 192 144 120 156]
 [195 169 234 156 169 208 247 195 156 143 247 208 20

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

In [76]:
points = np.array([[0, 1], [1, 0], [2, 3], [3, 2]])

differences = points[:, np.newaxis, :] - points[np.newaxis, :, :]
distances = np.sqrt(np.sum(differences ** 2, axis=-1))

print(distances)


[[0.         1.41421356 2.82842712 3.16227766]
 [1.41421356 0.         3.16227766 2.82842712]
 [2.82842712 3.16227766 0.         1.41421356]
 [3.16227766 2.82842712 1.41421356 0.        ]]


---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

In [58]:
student = np.array([('Moreen', 24, 154), ('Jane', 27,176), ('Too', 30,156)],
                   dtype = [('name',(np.str_,10)), ('age',np.int32), ('weight',np.float64)])
student 

array([('Moreen', 24, 154.), ('Jane', 27, 176.), ('Too', 30, 156.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

In [ ]:
five = np.random.randint(5,40, size=(5,5))
print(five) 
np.unique(five)

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

In [ ]:
three_m = np.random.randint(1,15, size = (3,3))
print(three_m)
mean = np.mean(three_m)
print(mean)
x_mean = np.subtract(three_m, mean)
print(x_mean)

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

In [ ]:
num1 = np.random.randint(1,100, size = 20)
num1 
n= 50
i = 1
if num1[i] > n:
    print("greater than 50")
else:
    print("Less than 50")


---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

In [75]:
f = np.arange(10,29)
print(f)
mean = np.mean(f)
print(mean)
np.ma.average(f)#, axis = 0, weights = 2 )


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]
19.0


19.0

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

In [ ]:
x_1 = np.linspace(13,100)
print("First List<", x_1)
x_2 = np.linspace(10,150)
print("Second list", x_2)
pearson = np.corrcoef(x_1,x_2)
print(pearson)

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

In [ ]:
radian = 2.12
degree = np.degrees(radian)
degree

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

In [ ]:
sampl = np.random.randint(25,50,size = 20)
sampl
mean= np.mean(sampl)
print(mean)
var = np.var(sampl)
print(var)

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

In [ ]:
H = np.random.randint(1,12, size = (2,2))
print(H)
row_max = np.max(H, axis =1)
col_max = np.max(H, axis =0)
print("Maximum in row,",row_max)
print("Maximum in Colunms,",col_max)

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

In [ ]:
g = np.random.randint( 10,20, size =(2,2))
g
np.linalg.inv(g)

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

In [ ]:
random_arr = np.random.randint(1,10,size =10)
print(random_arr )
average = np.mean(random_arr, axis = 0)
print(average)
stand = np.std(random_arr, axis = 0)
print(stand)
stand_ran = (random_arr -(average))/stand
np.mean(stand_ran, axis = 0)
np.std(stand_ran, axis = 0)
#XNormed = (X - np.mean(X, axis=0))/np.std(X, axis=0)
#column_mean = np.mean(XNormed, axis=0)
#print(column_mean)

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

In [ ]:
r_1 = np.random.randint(19,29, size = 6)
print("First array", r_1)
r_2 = np.random.randint(23,33,size = 6)
print("Second array ", r_2)
sum_1= np.add(r_1,r_2)
print("The sum of the two array is", sum_1)

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

In [ ]:
number_1 = np.arange(10,19)
print(number_1)
print(np.max(number_1))
maxindex = np.argmax(number_1)
print(maxindex)


---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

In [ ]:
r = np.random.randint(2,12, size =(3,3))
print(r)
np.rot90(r)

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

In [ ]:
from numpy import linalg
M = np.random.randint(10,20 ,size = (2,2))
M_1 =linalg.norm(M)
M_1

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---

In [ ]:
Three = np.arange(9).reshape((3,3))
Three
np.split(Three, 3)